September 2022 notes and October Stubb
planetarysoftware/ISIS_TC pull request #168
Opened 2022-09-21 19:44 UTC by jessemapel

2022-09-21 19:47 UTC, rbeyer commented on meetings/2022-09-08.md
> +      - doesn't have bagged
"baggage" I assume?

2022-09-21 19:49 UTC, rbeyer commented on meetings/2022-10-13.md
> +
Follow up discussion on https://github.com/planetarysoftware/ISIS_TC/issues/167

2022-09-21 19:50 UTC, rbeyer requested changes
Typo in notes, and suggested agenda item for Oct.

2022-09-21 20:19 UTC, rbeyer approved these changes

2022-10-12 13:06 UTC, jlaura commented
All - I am not sure that I will be able to attend this call tomorrow as it is fall break for the family and I will be out of town. I will make every attempt to join. 

I want to note that there is *still* no discussion on [#5029](https://github.com/USGS-Astrogeology/ISIS3/issues/5029) about concrete issues with GTest conversion and test writing. As I indicated in #167, from my perspective, the generic complaining with no realistically actionable input is counterproductive at best. It is my hope that concrete and actionable discussion occurs on [#5029](https://github.com/USGS-Astrogeology/ISIS3/issues/5029) and/or on some issue in this repository.

2022-10-12 13:06 UTC, jlaura approved these changes

2022-10-12 15:55 UTC, merged